name: Publish
on:
    push:
        branches: [ '**' ]
        paths-ignore: [ '**.md' ]
    workflow_call:
        secrets:
            MAVEN_USERNAME:
                required: false
            MAVEN_PASSWORD:
                required: false
            ORG_GRADLE_PROJECT_mavenCentralPassword:
                required: false
            ORG_GRADLE_PROJECT_mavenCentralUsername:
                required: false
            ORG_GRADLE_PROJECT_signingInMemoryKey:
                required: false
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword:
                required: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup Java
                uses: actions/setup-java@v3
                with:
                    distribution: zulu
                    java-version: 11
                    cache: gradle

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Build
                run: ./gradlew build
